import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import styles from "./styles.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'sans-serif' }}>
        <div className={styles.layoutRoot}>
          <aside className={styles.sidebar}>
            <div className={styles.sidebarTop}>
              <div className={styles.logoArea}>
                <span className={styles.logoDots}>⋮⋮⋮</span>
              </div>
              <nav className={styles.navVertical}>
                <Link href="/dashboard" className={styles.navLink}>
                  <span className={styles.navIcon}>📊</span> Dashboard
                </Link>
                <Link href="/import-csv" className={styles.navLink}>
                  <span className={styles.navIcon}>📁</span> Import CSV
                </Link>
              </nav>
            </div>
          </aside>
          <main className={styles.mainContent}>{children}</main>
        </div>
      </body>
    </html>
  );
}
