# Generated by Django 5.2.3 on 2025-06-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_assure', models.CharField(max_length=100, unique=True)),
                ('periode_exposition', models.FloatField(help_text="Durée d'assurance en années")),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=10)),
                ('experience', models.IntegerField(help_text='Années de permis')),
                ('type_vehicule', models.CharField(max_length=100)),
                ('zone_geographique', models.CharField(max_length=100)),
                ('usage', models.CharField(max_length=100)),
                ('historique', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sinistre', models.DateField()),
                ('montant', models.FloatField()),
                ('assure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistres', to='assurance.assure')),
            ],
        ),
    ]
